// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMXWPTuQUygeTM3Q91fsiMrybjcDzVYdU',
    appId: '1:753103954376:web:e2c30d2c4e6ae5dea120fd',
    messagingSenderId: '753103954376',
    projectId: 'socialqr-d2f3e',
    authDomain: 'socialqr-d2f3e.firebaseapp.com',
    storageBucket: 'socialqr-d2f3e.appspot.com',
    measurementId: 'G-D954H900RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8qr9dRtBJyb_Q8ygIh3iz1WC8Yp0J5iQ',
    appId: '1:753103954376:android:f06e8a41b54fc227a120fd',
    messagingSenderId: '753103954376',
    projectId: 'socialqr-d2f3e',
    storageBucket: 'socialqr-d2f3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe8T2Rs8giKUVsvjsAIJPs-OhReUBa-74',
    appId: '1:753103954376:ios:7fa2eb7db4604adba120fd',
    messagingSenderId: '753103954376',
    projectId: 'socialqr-d2f3e',
    storageBucket: 'socialqr-d2f3e.appspot.com',
    iosBundleId: 'com.socialqr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe8T2Rs8giKUVsvjsAIJPs-OhReUBa-74',
    appId: '1:753103954376:ios:6a6c179a9db3594ca120fd',
    messagingSenderId: '753103954376',
    projectId: 'socialqr-d2f3e',
    storageBucket: 'socialqr-d2f3e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMXWPTuQUygeTM3Q91fsiMrybjcDzVYdU',
    appId: '1:753103954376:web:d129e4c65f1e398aa120fd',
    messagingSenderId: '753103954376',
    projectId: 'socialqr-d2f3e',
    authDomain: 'socialqr-d2f3e.firebaseapp.com',
    storageBucket: 'socialqr-d2f3e.appspot.com',
    measurementId: 'G-MQTVEKM7D0',
  );
}
